local transf = require 'transf'
local vec3 = require 'vec3'
local vec4 = require 'vec4'
local modulesutil = require 'modulesutil'
local trainstationutil = require 'modules/elevated_trainstationutil'
local dump = require("luadump")
local lolloConstants = require("lolloConstants")

function data()
    return {
        availability = {
            yearFrom = lolloConstants().availableFrom, -- was 0
            --yearTo = -1 -- no!
        },
        cost = {
            price = 2000
        },
        description = {
            name = _('Elevated station'),
            description = _('Elevated station for passengers with street access.'),
            --icon = 'ui/construction/station/rail/modular_station/stairs.tga'
       		icon = "ui/elevated_stairs.tga"
        },
        category = {
            categories = {'elevated passenger buildings'}
        },
        metadata = {
            -- era = 1,
            -- level = 1,
            span = {1, 2}
        },
        type = 'elevated_rail_stairs',
        order = {
            value = 700
        },
        updateFn = function(result, transform, tag, slotId, addModuleFn, params)
            local faces = {
                {5.0, -5.0, 0.0, 1.0},
                {5.0, 5.0, 0.0, 1.0},
                {-1.0, 5.0, 0.0, 1.0},
				{-1.0, -5.0, 0.0, 1.0},
            }
            modulesutil.TransformFaces(transform, faces)
			local faces2 = {
				type = 'EQUAL', 
				faces = {faces},
				slopeHigh = 99, --LOLLO added this
				slopeLow = 0, --LOLLO added this
			}
            table.insert(result.terrainAlignmentLists, faces2)

            table.insert(
                result.groundFaces,
                {
                    face = faces,
                    modes = {
                        {
                            type = 'FILL',
                            key = 'shared/asphalt_01.gtex.lua'
                        },
                        {
                            type = 'STROKE_OUTER',
                            key = 'street_border.lua'
                        }
                    }
                }
            )

			--addModuleFn('station/rail/era_a/stairs.mdl', transf.rotZTransl(math.rad(90), vec3.new(0, 0, trainstationutil.getZed(params))))
			--addModuleFn('elevated_stairs.mdl', transf.rotZTransl(math.rad(90), vec3.new(0, 0, trainstationutil.getZed(params))))

			local transf1 = transf.rotZTransl(math.rad(90), vec3.new(0, 0, trainstationutil.getZed(params)))
			addModuleFn('elevated_stairs.mdl', transf1)
        end,
        getModelsFn = function()
            local result = {
                {
                    id = 'elevated_stairs.mdl', --'station/rail/era_a/stairs.mdl',
                    transf = transf.rotZTransl(math.rad(90), vec3.new(0, 0, 0))
                }
            }

            return result
        end
    }
end
