local transf = require 'transf'
local vec3 = require 'vec3'
local modulesutil = require 'modulesutil'
local trainstationutil = require 'modules/elevated_trainstationutil'
local lolloConstants = require("lolloConstants")

function data()
    return {
        availability = {
            yearFrom = lolloConstants().availableFrom, -- was 1925
            yearTo = 0
        },
        cost = {
            price = 30000
        },
        category = {
            categories = {'elevated tracks'}
        },
        description = {
            name = _('Elevated high-speed tracks'),
            description = _('Elevated tracks for higher speeds.'),
            icon = 'ui/construction/station/rail/modular_station/high_speed.tga'
        },
        -- buildMode = "MULTI",
        type = 'track',
        edgeType = 'BRIDGE',
        edgeTypeName = 'lollo_cement.lua',
        order = {
            value = 350
        },
        metadata = {
            track = true
        },
        updateFn = function(result, transform, tag, slotId, addModuleFn, params)
            trainstationutil.makeTrack(result, transform, tag, slotId, addModuleFn, params, 3)
        end,
        getModelsFn = function()
            local result = {}

            return result
        end
    }
end
