local transf = require "transf"
local vec3 = require "vec3"
local modulesutil = require "modulesutil"
local trainstationutil = require "modules/elevated_trainstationutil"
local lolloConstants = require("lolloConstants")

function data()

return { 
	availability = {
		yearFrom = lolloConstants().availableFrom, -- was 0
		yearTo = 0,
	},
	cost = {
		price = 18000,
	},
	description = {
		name = _("Elevated tracks"),
		description = _("Elevated tracks with limited speed capabilities."),
		icon = "ui/construction/station/rail/modular_station/track.tga"
	},
	type = "track",
	edgeType = "BRIDGE",
	edgeTypeName = "lollo_cement.lua",
	order = {
		value = 250,
	},
	metadata = {
		track = true,
	},
	category = {
		categories = { "elevated tracks", },
	},
	--buildMode = "MULTI",
	
	updateFn = function(result, transform, tag, slotId, addModuleFn, params)
		trainstationutil.makeTrack(result, transform, tag, slotId, addModuleFn, params, 1)
	end,
	
	getModelsFn = function()
		
		local result = {
		}
		
		return result
	end
}

end
