local lolloConstants = require('lollo_elevated_stations/lolloConstants')
local pedestrianGroundAreaHelper = require('lollo_elevated_stations.pedestrianGroundAreaHelper')
local transf = require 'transf'
local vec3 = require 'vec3'

function data()
    return {
        availability = {
            yearFrom = lolloConstants().availableFrom -- was 0
            --yearTo = -1 -- no!
        },
        cost = {
            price = 1000
        },
        description = {
            name = _('Passenger Area With Ads'),
            description = _('Passenger area with ads, to be placed under the station bridge, with pedestrian connections and street access.'),
            icon = 'ui/pedestrian_ground_area_ads.tga'
        },
        category = {
            categories = {'elevated passenger buildings'}
        },
        metadata = {
            -- era = 1,
            -- level = 1,
            span = {1, 2},
            stock_station = false -- LOLLO NOTE use this to override the default station handling
        },
        type = 'pedestrian_ground_area',
        order = {
            value = 704
        },
        updateFn = function(result, transform, tag, slotId, addModuleFn, params)
            pedestrianGroundAreaHelper.updateFn(result, transform, tag, slotId, addModuleFn, params)

            local function addRandomObjects(models, transformation)
                addModuleFn(
                    models[math.random(#models)],
                    transformation
                )
            end

            local rndPlusOrMinusOne = math.random(2) * 2 - 3
            local models = {
                'station/bus/asset/com_round_new_1.mdl',
                'station/bus/asset/com_round_mid_1.mdl',
                'station/bus/asset/com_round_old_1.mdl',
                'station/bus/asset/com_small_mid_1.mdl',
                'station/bus/asset/com_small_mid_2.mdl',
                'station/bus/asset/com_small_new_1.mdl',
                'station/bus/asset/com_small_new_2.mdl',
                'asset/arrivi_partenze_colonna_new.mdl',
                'asset/arrivi.mdl',
                'asset/partenze.mdl',
                -- 'station/bus/asset/tickets_mid_1.mdl',
                -- 'station/bus/asset/bench_mid_l3.mdl',
                -- 'station/bus/asset/tickets_new_1.mdl',
                -- 'asset/commercial/era_b/com_1_asset_ground_sign_food_small_a.mdl',
                -- 'asset/commercial/era_b/com_1_asset_ground_sign_food_small_b.mdl',
                -- 'asset/commercial/era_b/com_1_asset_ground_sign_rest_small_a.mdl',
                -- 'asset/commercial/era_b/com_1_asset_ground_sign_rest_small_b.mdl',
                -- 'station/air/asset/cart_baggage_b.mdl',
            }
            addRandomObjects(models, transf.rotZTransl(math.rad(60), vec3.new(1.0, -rndPlusOrMinusOne * 5, 0)))
            addRandomObjects(models, transf.rotZTransl(math.rad(120), vec3.new(-1.5, -rndPlusOrMinusOne * 1.5, 0)))

            addModuleFn(
                -- 'asset/bench_dark_red.mdl',
                'station/rail/asset/era_c_double_chair.mdl',
                transf.rotZTransl(math.rad(0), vec3.new(0.9, rndPlusOrMinusOne * 4.9, 0))
            )
            addModuleFn(
                -- 'asset/bench_dark_red.mdl',
                'station/rail/asset/era_c_double_chair.mdl',
                transf.rotZTransl(math.rad(180), vec3.new(-0.9, rndPlusOrMinusOne * 4.9, 0))
            )
            local rndPlusOrMinusOne2 = math.random(2) * 2 - 3
            addModuleFn(
                'station/rail/asset/era_c_trashcan.mdl',
                transf.rotZTransl(math.rad(-rndPlusOrMinusOne2 * 25), vec3.new(rndPlusOrMinusOne2 * 1.5, rndPlusOrMinusOne * 1.5, 0))
            )

            local models = {
                'station/air/asset/luggage_01_a.mdl',
                'station/air/asset/luggage_01_b.mdl',
                'station/air/asset/luggage_02_a.mdl',
                'station/air/asset/luggage_02_b.mdl',
                'station/air/asset/luggage_03_a.mdl',
                'station/air/asset/luggage_03_b.mdl',
            }
            addRandomObjects(models, transf.rotZTransl(3 * (math.random()), vec3.new(0.8, rndPlusOrMinusOne * 3.3, 0)))
            addRandomObjects(models, transf.rotZTransl(3 * (math.random()), vec3.new(-0.5, rndPlusOrMinusOne * 3.2, 0)))
            addRandomObjects(models, transf.rotZTransl(3 * (math.random()), vec3.new(-0.9, rndPlusOrMinusOne * 3.7, 0)))
        end,
        getModelsFn = function()
            local result = {
                {
                    id = 'pedestrian_ground_areas/poles.mdl',
                    transf = transf.rotZTransl(math.rad(90), vec3.new(0, 0, 0))
                }
            }

            return result
        end
    }
end
