local transf = require 'transf'
local vec3 = require 'vec3'
-- local vec4 = require 'vec4'
local modulesutil = require 'modulesutil'
local arrayUtils = require('lollo_elevated_stations.arrayUtils')
local lolloConstants = require('lollo_elevated_stations/lolloConstants')

function data()
    return {
        availability = {
            yearFrom = lolloConstants().availableFrom -- was 0
            --yearTo = -1 -- no!
        },
        cost = {
            price = 1000
        },
        description = {
            name = _('Plain Station Square'),
            description = _('Small square to be placed in front or behind a station, with street access.'),
            icon = 'ui/station_square_plain.tga'
        },
        category = {
            categories = {'elevated passenger buildings'}
        },
        metadata = {
            -- era = 1,
            -- level = 1,
            span = {1, 2},
            stock_station = false -- LOLLO NOTE use this to override the default station handling
        },
        type = 'station_square_plain',
        order = {
            value = 702
        },
        updateFn = function(result, transform, tag, slotId, addModuleFn, params)
            local _isWithGap = arrayUtils.arrayHasValue(result.plainSquaresWithGap, slotId)

            local faces = _isWithGap and {
                {2.5, -5.8, 0.0, 1.0},
                {2.5, 9.8, 0.0, 1.0},
                {-2.5, 9.8, 0.0, 1.0},
                {-2.5, -5.8, 0.0, 1.0}
            } or {
                {2.5, -5.8, 0.0, 1.0},
                {2.5, 5.8, 0.0, 1.0},
                {-2.5, 5.8, 0.0, 1.0},
                {-2.5, -5.8, 0.0, 1.0}
            }
            modulesutil.TransformFaces(transform, faces)
            local faces2 = {
                type = 'EQUAL',
                faces = {faces},
                optional = true
                -- slopeHigh = 999, --LOLLO added this
                -- slopeLow = 0 --LOLLO added this
            }
            table.insert(result.terrainAlignmentLists, faces2)
            -- LOLLO NOTE insert colliders here, coz those in the model do not pull.
            -- These values are calculated with trial and error. They are slightly larger than half of the bounding box sizes, which are cut a tad smaller.
            table.insert(
                result.colliders,
                {
                    type = 'BOX',
                    transf = transf.mul(transform, transf.transl(vec3.new(0, 0, 5))), --transform,
                    params = {
                        halfExtents = {5.8, 2.5, 3}
                    }
                }
            )

            table.insert(
                result.groundFaces,
                {
                    face = faces,
                    modes = {
                        {
                            type = 'FILL',
                            key = 'shared/asphalt_01.gtex.lua' --'shared/asphalt_01.gtex.lua'
                        },
                        --[[                         {
                            type = 'STROKE_INNER',
                            key = 'shared/asphalt_01.gtex.lua',
                        },
                        ]]
                        {
                            type = 'STROKE_OUTER',
                            key = 'shared/asphalt_01.gtex.lua' --'street_border.lua'
                        }
                    }
                }
            )

            addModuleFn(
                'station_square_plain.mdl',
                transf.rotZTransl(math.rad(90), vec3.new(0, 0, 0))
            )

            if _isWithGap then
                addModuleFn(
                    'between_plain_squares.mdl',
                    transf.rotZTransl(math.rad(0), vec3.new(0, 8, 0))
                )
            end

        end,
        getModelsFn = function()
            local result = {
                {
                    id = 'station_square_plain.mdl',
                    transf = transf.rotZTransl(math.rad(90), vec3.new(0, 0, 0))
                }
            }

            return result
        end
    }
end
